### ISSUE TITLE
Produces Json

### ISSUE THREAD

**Issue by SamuelRocha2015** [apljjr/mapFood#5]
https://github.com/apljjr/mapFood/blob/f6df42851d5aa0e9d0cd8f0811f216bd1ab9c2e2/mapfood-api/src/main/java/br/com/codenation/mapfood/resource/RestaurantsResource.java#L34

Existe algum motivo específico para setar o **_produces_** ? Por default não precisa colocar.

**Comment by apljjr** [comment]
Não existe um motivo específico.

Fui ler a documentação e realmente já é default.

produces
@AliasFor(annotation=RequestMapping.class)
public abstract java.lang.String[] produces
Alias for RequestMapping.produces().
Default:
{}
