### ISSUE TITLE
Nomenclatura dos folders

### ISSUE THREAD

**Issue by SamuelRocha2015** [apljjr/mapFood#6]
Fiquei com dúvida em relação aos nomes dos pacotes: 
- document
- resource

Vocês viram em algum lugar esse padrão ?

**Comment by apljjr** [comment]
O pacote resource foi colocado para seguir o modelo orientado a recursos utilizado na Arquitetura REST, em vez do MVC do Spring que utiliza o controller.

Já o document é utilizado por estarmos trabalhando com mongoDB. Não temos mais o conceito de entidade e sim de documentos para manipulação do banco mongo.
